version: '3.7'

# Service
services:
  # Database MySQL
  app-db:
    image: mysql:8.0.17
    container_name: app-db
    #restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mms_db
      MYSQL_USER: springboot
      MYSQL_PASSWORD: springboot
    ports:
      - "3306:3306"
    networks:
      - app-server-network
  # APP Server
  app-server:
    depends_on:
      - app-db
    #restart: always
    image: mms/member-manage-system:0.0.1
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
#    links:
#      - app-db
    environment: # Pass environment variables to the service
      DATASOURCE_HOST: app-db
      DATASOURCE_POST: 3306
      DATASOURCE_NAME: mms_db
      DATASOURCE_USERNAME: springboot
      DATASOURCE_PASSWORD: springboot
    networks:
      - app-server-network
    command: ["./wait-for-it.sh", "app-db:3306", "--", "java", "-jar", "mms.war"]
#    command: ["wait-for-it.sh", "java", "-jar", "mms.war"]

# Volume
volumes:
    mysql-data:

# Network
networks:
  app-server-network:
